# Generated by Django 5.2.18 on 2026-10-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hotel', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('category', models.CharField(choices=[('Hotels', 'Hotels'), ('Resorts', 'Resorts'), ('Homestays', 'Homestays'), ('Villas', 'Villas'), ('Houseboats', 'Houseboats')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imageUrl', models.CharField(max_length=1000)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=10)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_suite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
